title: My wavy words
hero_image: images/banner.png
description: Draw some visual poetry.
listed: false
landing: true
pdf: false
steps:
  - title: Step 1
  - title: Step 2
    completion:
      - engaged      
  - title: Step 3
  - title: Step 4
  - title: Step 5
  - title: Step 6
  - title: Step 7
  - title: Step 8
    challenge: true
    completion:
      - external
